
import { getServerSession } from 'next-auth';
import '@/styles/globals.css'
import SessionProvider from '@/app/(web)/components/SessionProvider'
import AppWrapper from '@/app/(web)/components/appWrapper';
import NextAuthClientSessionProvider from '@/components/NextAuthClientSessionProvider';

export const metadata = {
  title: 'Patreon Clone',
  description: 'Generated by create next app',
  
}

export default async function RootLayout({ children }) {
  // const session = await getServerSession()
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link rel='icon' href="favicon.ico" />
      </head>
      <body style={{ minHeight: "100vh" }}>
        {/* <SessionProvider session={session}> */}
          <NextAuthClientSessionProvider>
            <AppWrapper>
              {children}
            </AppWrapper>
          </NextAuthClientSessionProvider>
        {/* </SessionProvider> */}
      </body>
    </html>
  )
}
