import '@/app/styles/globals.css'

import AppWrapper from '@/app/(web)/components/appWrapper';

export const metadata = {
  title: 'Patreon Clone',
  description: 'Generated by create next app',
  
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body style={{ minHeight: "100vh" }}>
        <AppWrapper>
          {children}
        </AppWrapper>
      </body>
    </html>
  )
}
